title: "Washed 'N Worn"
author: David Giorgi
email: busgiorgi@gmail.com
description: >-
  Home

social:
  instagram: _washednworn
  linkedin: David Giorgi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
