title: "Washed 'N Worn"
author: David Giorgi
email: busgiorgi@gmail.com
description: >-
  Washed 'N Worn!

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
